//! Tests for the error surfacing of `ApplyMethod::SuccessiveRandomized`
//! (SRC): the elementwise result-boundary scans, and the check that
//! rejects a QR factorization degenerated by a panel column norm past
//! the scalar's range.
//!
//! Split out of the main SRC test module because error surfacing is a
//! distinct reading unit from the exactness and structure tests. The
//! fixtures come in two kinds: plain `NAN` / `INFINITY` planted in an
//! input, and elementwise-finite states at magnitudes that overflow an
//! intermediate. Only the second kind carries a measured tuning window,
//! stated per test.

use ariadnetor_mps::{
    self as mps, ApplyMethod, Mps, SuccessiveRandomizedParams, TensorChain,
    apply_sum_successive_randomized,
};
use ariadnetor_native::NativeBackend;
use ariadnetor_tensor::{DenseLayout, DenseStorage};

use super::helpers::{
    cm_dense_tensor, fixed_rank_src_params, make_3site_test_mpo, make_3site_test_mps,
    make_4site_mps, make_identity_mpo, make_total_n_dense_mpo, with_site_scaled,
};

/// Unpack the expected `NonFinite` error into its `(site, norm)`
/// diagnostics, panicking on `Ok` or any other variant.
fn expect_non_finite(
    res: Result<Mps<DenseStorage<f64>, DenseLayout>, mps::ApplyError>,
) -> (usize, f64) {
    match res {
        Ok(_) => panic!("a poisoned input must not be returned as a success"),
        Err(mps::ApplyError::NonFinite { site, norm }) => (site, norm),
        Err(other) => panic!("expected NonFinite, got {other:?}"),
    }
}

#[test]
fn src_adaptive_surfaces_nan_input_as_error() {
    let backend = NativeBackend::new();
    let mut psi = make_3site_test_mps();
    let op = make_3site_test_mpo();
    psi.site_mut(0).set([0, 0, 0], f64::NAN);

    let method = ApplyMethod::SuccessiveRandomized(SuccessiveRandomizedParams::default());
    let (site, norm) = expect_non_finite(mps::apply_with_method(&backend, &op, &psi, None, method));
    // Every sketch panel folds the environments of all sites to its
    // left, so input poison anywhere surfaces at the first processed
    // site of the right-to-left sweep.
    assert_eq!(site, 2, "detection happens at the first processed site");
    assert!(norm.is_nan(), "the diagnostic carries the offending norm");
}

#[test]
fn src_fixed_mode_surfaces_inf_input_as_error() {
    let backend = NativeBackend::new();
    let psi = make_3site_test_mps();
    let mut op = make_3site_test_mpo();
    op.site_mut(1).set([0, 0, 0, 0], f64::INFINITY);

    // Fixed mode never consults the adaptive stopping rule, so the check
    // must fire on the single panel pass itself.
    let method = ApplyMethod::SuccessiveRandomized(fixed_rank_src_params(2, 0));
    let (site, norm) = expect_non_finite(mps::apply_with_method(&backend, &op, &psi, None, method));
    assert_eq!(site, 2, "detection happens at the first processed site");
    // The inf may surface as inf directly or as NaN through an
    // `inf - inf` / `0 * inf` in the contraction sums.
    assert!(
        !norm.is_finite(),
        "the diagnostic carries the offending norm"
    );
}

#[test]
fn src_adaptive_surfaces_panel_norm_overflow_as_error() {
    let backend = NativeBackend::new();
    // Past the saturation window of the test above: here a growth
    // round's panel norm itself exceeds f64::MAX with every element
    // finite, so the backend QR cannot produce a finite triangular
    // factor and the stopping rule has nothing to certify against. The
    // sweep must error instead of accepting the round as rank-deficient
    // coverage and returning a bond-stuck state as a success.
    // Tuning (same measured norms): the first processed site's largest
    // panel norm is ~874.6x the scale — overflowing from ~2.06e305 up —
    // and its elements stay finite until ~2.5e305; beyond that the
    // elementwise panel scan fires first (same error, older path).
    // Re-tune if the fixture, seed, or random stream ever changes.
    let psi = make_4site_mps();
    let op = make_total_n_dense_mpo(4);
    let scale = 2.2e305;
    let scaled = with_site_scaled(&psi, 0, scale);
    let method = ApplyMethod::SuccessiveRandomized(SuccessiveRandomizedParams {
        cutoff: Some(1e-6),
        sketch_dim: 1,
        sketch_increment: 1,
        seed: 42,
        ..Default::default()
    });
    let (site, norm) =
        expect_non_finite(mps::apply_with_method(&backend, &op, &scaled, None, method));
    // The right-to-left sweep hits the overflowing growth round at the
    // first processed site; the diagnostic carries the degenerated QR
    // diagonal (inf or NaN is a backend detail).
    assert_eq!(site, 3, "detection happens at the first processed site");
    assert!(!norm.is_finite(), "the diagnostic carries the degeneration");
}

#[test]
fn src_single_site_surfaces_nan_as_error() {
    let backend = NativeBackend::new();
    // The n == 1 path has no sketch: the exact local product itself is
    // the checked boundary quantity.
    let psi: Mps<DenseStorage<f64>, DenseLayout> =
        Mps::from_sites(vec![cm_dense_tensor(vec![1.0, f64::NAN], vec![1, 2, 1])]);
    let op = make_identity_mpo(1, 2);

    let method = ApplyMethod::SuccessiveRandomized(SuccessiveRandomizedParams::default());
    let (site, norm) = expect_non_finite(mps::apply_with_method(&backend, &op, &psi, None, method));
    assert_eq!(site, 0, "the single site is site 0");
    assert!(norm.is_nan(), "the diagnostic carries the offending norm");
}

/// Three-site chain carrying an extreme amplitude on site 0. Which
/// check the sweep trips is a function of `scale` alone, so the two
/// tests below share the fixture and differ only in that argument.
fn overflow_chain(scale: f64) -> Mps<DenseStorage<f64>, DenseLayout> {
    Mps::from_sites(vec![
        cm_dense_tensor(
            vec![1.0 * scale, 0.8 * scale, 0.9 * scale, 0.7 * scale],
            vec![1, 2, 2],
        ),
        cm_dense_tensor(vec![0.9, 0.5, 0.6, 1.0, 0.7, 0.8, 0.9, 0.6], vec![2, 2, 2]),
        cm_dense_tensor(vec![1.0, 0.6, 0.7, 1.0], vec![2, 2, 1]),
    ])
}

/// Fixed-rank SRC at bond dimension 1: one append per site, so the
/// terminal accessor returns a plain Householder factor unrepaired.
fn fixed_rank_1(seed: u64) -> ApplyMethod {
    ApplyMethod::SuccessiveRandomized(fixed_rank_src_params(1, seed))
}

#[test]
fn src_fixed_mode_surfaces_degenerated_qr_factor_as_error() {
    let backend = NativeBackend::new();
    // At this amplitude the sweep's panel keeps every element finite
    // while its column norm exceeds f64::MAX, so the QR append comes
    // back with a non-finite diagonal. The basis such a factorization
    // yields can be finite and still column-orthonormal while spanning
    // an arbitrary subspace, which no elementwise scan can see, so the
    // sweep errors at the panel's own site instead of assembling sites
    // from it. Fixed mode gets the same treatment as adaptive mode:
    // neither has anything to salvage.
    //
    // Measured for this fixture and seed: the panel's site reports from
    // ~1.15e308 up, and the assembled-sites scan owns ~3.9e307 to
    // ~1.10e308 (the test below); between and below those the sweep
    // succeeds. Re-tune if the fixture, seed, or random stream ever
    // changes.
    let psi = overflow_chain(1.2e308);
    let op = make_identity_mpo(3, 2);
    let (site, norm) = expect_non_finite(mps::apply_with_method(
        &backend,
        &op,
        &psi,
        None,
        fixed_rank_1(42),
    ));
    assert_eq!(
        site, 1,
        "the degenerated append reports at the panel's site"
    );
    assert!(
        norm.is_infinite(),
        "the diagnostic carries the degenerated QR diagonal"
    );
}

#[test]
fn src_fixed_mode_surfaces_assembled_site_overflow_as_error() {
    let backend = NativeBackend::new();
    // The same fixture one window lower: every panel column norm stays
    // representable, so no append degenerates, and the overflowed
    // weight lands in the site tensors assembled after the sweep
    // instead. This is the deterministic exercise of the
    // assembled-sites scan, the check covering poison that arises past
    // the last panel — inside the QR itself, the cap updates, or the
    // first-site contraction.
    //
    // Measured window for this fixture and seed: ~3.9e307 to ~1.10e308.
    // Re-tune if the fixture, seed, or random stream ever changes.
    let psi = overflow_chain(7.0e307);
    let op = make_identity_mpo(3, 2);
    let (site, norm) = expect_non_finite(mps::apply_with_method(
        &backend,
        &op,
        &psi,
        None,
        fixed_rank_1(42),
    ));
    assert_eq!(
        site, 0,
        "the assembled-sites scan reports the site it scanned"
    );
    assert!(norm.is_infinite(), "the diagnostic carries the overflow");
}

#[test]
fn src_fixed_mode_rejects_span_collapsed_basis() {
    let backend = NativeBackend::new();
    // The regression the degenerated-factor check exists for, and the
    // reason no state inspection can replace it. Every panel and every
    // assembled site here is elementwise finite, so every scan passes,
    // and the state carries `Mixed { center: 0 }` over sites that are
    // genuinely right-isometric, so the metadata holds too. What is
    // wrong is the last site's value: its overflowed panel column
    // collapses onto the first basis vector, giving `[1, 0]` where the
    // true direction is the normalization of `[1, 1.1]`. Absent the
    // check the sweep hands that back as a success and the caller gets
    // no signal, so what this test pins is the absence of an `Ok` —
    // which is what `expect_non_finite` asserts, the site index below
    // being the detection locus rather than a separate claim.
    //
    // Bond dimension 1 with the amplitude on the last site alone keeps
    // the environment recursion at unit magnitude, so only the final
    // panel overflows; the fixture above cannot reach this state,
    // because its own overflow trips a scan first. Measured window for
    // this seed: ~4.9e307 to ~1.1e308. Re-tune if the fixture, seed, or
    // random stream ever changes.
    let amp = 1.0e308;
    let psi: Mps<DenseStorage<f64>, DenseLayout> = Mps::from_sites(
        (0..3)
            .map(|i| {
                let a = if i == 2 { amp } else { 1.0 };
                cm_dense_tensor(vec![a, a * 1.1], vec![1, 2, 1])
            })
            .collect(),
    );
    let op = make_identity_mpo(3, 2);
    let (site, norm) = expect_non_finite(mps::apply_with_method(
        &backend,
        &op,
        &psi,
        None,
        fixed_rank_1(28),
    ));
    assert_eq!(
        site, 2,
        "the right-to-left sweep starts at the last site, where the panel overflows"
    );
    assert!(
        norm.is_infinite(),
        "the diagnostic carries the degenerated QR diagonal"
    );
}

#[test]
fn src_sum_surfaces_degenerated_qr_factor_as_error() {
    let backend = NativeBackend::new();
    // The three SRC entry points share one sweep, but a shared mechanism
    // is not shared coverage: each documents the degenerated-factor
    // error on its own `# Errors` section, so each is pinned. Here the
    // linear-combination entry runs the fixture as a single
    // coefficient-one term, which the sum kernel's bypass makes
    // arithmetically identical to the single-pair sweep.
    let psi = overflow_chain(1.2e308);
    let op = make_identity_mpo(3, 2);
    let (site, norm) = expect_non_finite(apply_sum_successive_randomized(
        &backend,
        &[(&op, &psi)],
        &[1.0],
        None,
        fixed_rank_src_params(1, 42),
    ));
    assert_eq!(
        site, 1,
        "the degenerated append reports at the panel's site"
    );
    assert!(
        norm.is_infinite(),
        "the diagnostic carries the degenerated QR diagonal"
    );
}

#[test]
fn src_round_surfaces_degenerated_qr_factor_as_error() {
    let backend = NativeBackend::new();
    // The rounding entry builds its own identity MPO and runs the same
    // sweep without a finishing pass. Its contract adds that `self` is
    // left unmodified on the error path, so the chain is compared
    // against a clone taken beforehand.
    let mut psi = overflow_chain(1.2e308);
    let before: Vec<Vec<f64>> = (0..psi.len())
        .map(|j| psi.site(j).data_slice().to_vec())
        .collect();
    let err = psi
        .round_successive_randomized(&backend, fixed_rank_src_params(1, 42))
        .expect_err("the degenerated append must not round to a success");
    let mps::ApplyError::NonFinite { site, norm } = err else {
        panic!("expected NonFinite, got {err:?}");
    };
    assert_eq!(
        site, 1,
        "the degenerated append reports at the panel's site"
    );
    assert!(
        norm.is_infinite(),
        "the diagnostic carries the degenerated QR diagonal"
    );
    for (j, original) in before.iter().enumerate() {
        assert_eq!(
            psi.site(j).data_slice(),
            &original[..],
            "site {j} must be untouched when the round errors"
        );
    }
}

// The assembled-sites scan has no adaptive-mode deterministic test: with
// all panels finite and the factorization healthy it fires only when the
// QR internals, the cap update, or the first-site contraction alone go
// non-finite — a margin set by the Gaussian samples, so a triggering
// adaptive fixture would encode magic magnitudes tied to the RNG stream
// and break on a `rand` upgrade. The fixed-mode test above covers the
// scan itself; relative to the panel scans it stays defense in depth.
